### ISSUE TITLE
Не работает на sber tv box

### ISSUE THREAD

**Issue by Riko1515** [agolyud/VPN_Outline_TV#10]
Проблема в том, что не могу даже вбить ключ в окошко, при нажатие на окно ввода просто ничего не происходит, при двойных, тройных кликах на него, клавиатура появляется на секунду и исчезает обратно, пофиксите, пожалуйста, если есть возможность. Спасибо за работу!

**Comment by agolyud** [comment]
Приветствую. И не заработает к сожалению, в Sber tv нету com.android.vpndialogs.ConfirmDialog и из-за этого вы не подключитесь к ВПН. Единственный вариант вам использовать протокол wireguard, там вызывается по другому разрешение. Либо прошить приставку.
