### ISSUE TITLE
При добавлении ключа, пишет "Неверный формат ссылки"

### ISSUE THREAD

**Issue by JimDiGreez** [agolyud/VPN_Outline_TV#11]
В ссылке отсутствует @ и прочая, но в outline она работает

**Comment by agolyud** [comment]
пример ключа напишите свой

**Comment by Cintecele** [comment]
Аналогичная проблема. Формат ключа ss://Y2hhY2hhMjAta....@192.168.0.1:00000/?outline=1
При нажатии на "Подключиться" на секунду меняется иконка на зеленую "Подключено" и затем снова красная "Подключиться" с нулевым таймером. Сообщений об ошибках нет.

**Comment by agolyud** [comment]
версию последнюю качали?

**Comment by Cintecele** [comment]
Да, проверял на версиях 1.0.3 и 1.0.4

**Comment by agolyud** [comment]
версия 1.0.3 косячная. И версию 1.0.4 надо ставить на чисто перед этим удалить 1.0.3( поверх нельзя)

**Comment by agolyud** [comment]
Да мой косяк. Намудрил с парсером. Сегодня поправлю и выпущу новую версию

**Comment by alar1** [comment]
> Да мой косяк. Намудрил с парсером. Сегодня поправлю и выпущу новую версию

Очень ждем!

**Comment by agolyud** [comment]
Поправил: https://github.com/agolyud/VPN_Outline_TV/releases/tag/1.0.5
