### ISSUE TITLE
Apk файл

### ISSUE THREAD

**Issue by Rodjon13** [agolyud/VPN_Outline_TV#12]
Где находится сам apk файл для загрузки на тв?

**Comment by Rodjon13** [comment]
Правильно понимаю, я перегружаю папку на тв и открываю этот apk? Только не знаю что установщик

**Comment by agolyud** [comment]
Вот файл apk 
[OutlineVPNtv.apk](https://github.com/agolyud/VPN_Outline_TV/releases/download/1.0.4/OutlineVPNtv.apk)

**Comment by Rodjon13** [comment]
Спасибо
