### ISSUE TITLE
Enter key

### ISSUE THREAD

**Issue by Dmitry-7557** [agolyud/VPN_Outline_TV#13]
Very important ! Please add button for paste key from clipboard. I only can copy key from txt, but paste key in vpn app on android tv not available.

**Comment by agolyud** [comment]
Good point. I'll add it to version 1.0.5.

**Comment by agolyud** [comment]
done ✅
https://github.com/agolyud/VPN_Outline_TV/releases/tag/1.0.5

**Comment by Dmitry-7557** [comment]
> done ✅ https://github.com/agolyud/VPN_Outline_TV/releases/tag/1.0.5

Thanks
