### ISSUE TITLE
Постоянная ссылка для скачивания

### ISSUE THREAD

**Issue by q1LLa** [agolyud/VPN_Outline_TV#15]
Добрый день. Можно как-то реализовать постоянную ссылку для скачивания последней версии приложения ?

Чтобы постоянно не менять в адресе ссылки версию приложения ?

**Comment by agolyud** [comment]
Добрый день. На неделе попробую придумать что то и реализовать

**Comment by q1LLa** [comment]
> Добрый день. На неделе попробую придумать что то и реализовать

Можно банально Bitly)

**Comment by Bansher** [comment]
Добрый день. Есть функция автоподключения?

**Comment by agolyud** [comment]
Добавил в новую версию. Завтра выпущу теперь он автоматически будет обновлять если вышла версия. Ожидайте 1.0.6

**Comment by q1LLa** [comment]
Автообновление это круто, но я имел ввиду, что ссылка для скачивания становится не рабочей после выхода новой версии, например - https://github.com/agolyud/VPN_Outline_TV/releases/download/1.0.5/OutlineVPNtv.apk 

Хотелось бы иметь одну ссылку, чтобы она сразу скачивала последнюю версию.

**Comment by agolyud** [comment]
Можно было бы загуглить как с github тянуть последнюю версию с релиза:

Вот так:
https://github.com/agolyud/VPN_Outline_TV/releases/latest/download/OutlineVPNtv.apk

он всегда будет качать последнюю версию.

**Comment by q1LLa** [comment]
> Можно было бы загуглить как с github тянуть последнюю версию с релиза:
> 
> Вот так: https://github.com/agolyud/VPN_Outline_TV/releases/latest/download/OutlineVPNtv.apk
> 
> он всегда будет качать последнюю версию.

Спасибо!
