### ISSUE TITLE
Feature request: Select DNS servers

### ISSUE THREAD

**Issue by tholden** [agolyud/VPN_Outline_TV#21]
It would be helpful to be able to select DNS servers.

**Comment by agolyud** [comment]
I will make the next update. There is still a lot of basic work to do

**Comment by agolyud** [comment]
@khoben Hi. If you have time. Maybe we can implement it together?

**Comment by tholden** [comment]
The DNS look ups are server side right (i.e. through the VPN)? I had a look at the Android help for VpnService.Builder but it wasn't particularly clear.

**Comment by khoben** [comment]
> @khoben Hi. If you have time. Maybe we can implement it together?

Hi,
[Its](https://github.com/agolyud/VPN_Outline_TV/blob/main/app/src/main/java/app/android/outlinevpntv/domain/VpnTunnel.java#L76-L83) already selecting random (?) DNS from the list. Just need to pass the specified DNS via parameters [here](https://github.com/agolyud/VPN_Outline_TV/blob/main/app/src/main/java/app/android/outlinevpntv/domain/OutlineVpnService.kt#L141). Also from here white/black list for applications that will use VPN can be passed ([addAllowedApplication](https://developer.android.com/reference/android/net/VpnService.Builder#addAllowedApplication(java.lang.String)), [addDisallowedApplication](https://developer.android.com/reference/android/net/VpnService.Builder#addDisallowedApplication(java.lang.String))).

I suggest making a settings button at the top and on the settings screen making DNS input and allowed/disallowed app packages selection and other related settings:
<details>
<summary>Main screen sample UI</summary>

![image](https://github.com/user-attachments/assets/213ab299-0fbf-475d-8538-dde14082c4d0)

</details>
<details>
<summary>Settings screen sample UI</summary>

![image](https://github.com/user-attachments/assets/51aebbe8-8016-4904-9936-26c0d9e63c72)

</details>

I suppose it's worth starting with implementing settings screen UI and then the other settings features (apps list, dns, autostart). I'll look into this next week.

**Comment by agolyud** [comment]
@khoben let me do the UI. And we create a branch and implement everything else in it.

**Comment by khoben** [comment]
> @khoben let me do the UI. And we create a branch and implement everything else in it.

👍

**Comment by agolyud** [comment]
@tholden https://github.com/agolyud/VPN_Outline_TV/releases/tag/1.0.7

**Comment by khoben** [comment]
Maybe it can be made easier with IP input and google or cloudflare by default? There may be other DNS, including self-hosted.

**Comment by agolyud** [comment]
it can be implemented but in the next version

**Comment by tholden** [comment]
Great, thanks to you both!
