### ISSUE TITLE
Ошибка "Не удалось запустить VPN"

### ISSUE THREAD

**Issue by zettrap** [agolyud/VPN_Outline_TV#22]
Телевизор: sony bravia 2k gb atv3

Ключ вида ssconf:

Загружаю ключ из файла.

Имя сервера оставляю пустым.

После нажатия на кнопку ошибка "Не удалось запустить VPN"

**Comment by zettrap** [comment]
Соответственно через приложение Outline на Windows и Android всё работает

**Comment by YaroslavGrud** [comment]
такая же проблема но с вылетом приложения на платформе СалютТВ (Сбер)

**Comment by q1LLa** [comment]
Такая же проблема на MiTV-MOSR1 (android 11)
Ключ динамический ssconf://
![IMG_5302](https://github.com/user-attachments/assets/c1c0605a-89c5-4bbc-ae3d-5db54656e57f)

**Comment by agolyud** [comment]
Если кто в лс предоставит ключ смогу глянуть из-за чего и поправить.

**Comment by agolyud** [comment]
https://github.com/agolyud/VPN_Outline_TV/releases/tag/1.0.7
