### ISSUE TITLE
Неправильный формат ключа Outline

### ISSUE THREAD

**Issue by Vel-Q** [agolyud/VPN_Outline_TV#25]
Возникли проблемы с ключем, который отлично работает на ПК, при вставке кода в приложение на телевизоре выходит ошибка.

Версия 1.0.8

Пример ключа ss://Y2hhY2hhMjAtaWV0Zi...#VPN

**Comment by agolyud** [comment]
Поправлен 

https://github.com/agolyud/VPN_Outline_TV/releases/tag/1.0.9
