### ISSUE TITLE
VPN_Outline_TV неверный формат ключа

### ISSUE THREAD

**Issue by nub309** [agolyud/VPN_Outline_TV#28]
После обновления не могу вписать ключ брал 3 разных выдает не правильный формат ключа ( ключ который вписывался первый раз ss://Y2hhY2hhMjAtaWV0Zi1wb2x5M

после решил поменять на таковоже типа не сохраняет.

**Comment by agolyud** [comment]
Ключ потер. Поправлю в следующем обновлении

**Comment by agolyud** [comment]
fix
https://github.com/agolyud/VPN_Outline_TV/releases/tag/1.1.0
