### ISSUE TITLE
Неверный формат ssconf

### ISSUE THREAD

**Issue by Junker-vv** [agolyud/VPN_Outline_TV#30]
Установил последнюю версию, и при загрузке ключа ssconf:// выдаёт неверный формат

**Comment by agolyud** [comment]
не могу проверить нет ключа такого. Если скинете в телеграм ключ я проверю и поправлю если там ошибка

**Comment by Junker-vv** [comment]
Здравствуйте. 
ssconf://oleg.loan/vanya/ab472986-fb36-4709-97d1-887102cacd02
Yahoo Почта: Поиск, организация, успех 
 
  ср, 27 нояб. 2024 в 9:33 ***@***.***> написал(-а):   


не могу проверить нет ключа такого. Если скинете в телеграм ключ я проверю и поправлю если там ошибка
