### ISSUE TITLE
Добавить поддержку нескольких ключей

### ISSUE THREAD

**Issue by Fearcatcher** [agolyud/VPN_Outline_TV#32]
Здравствуйте. Имеется несколько ключей с разными серверами Outline и иногда возникает потребность в переключении между ними. Не могли бы вы добавить функционал по добавлению нескольких ключей, и, соответственно, чтобы после добавления, была возможность выбрать сервер, который пользователь планирует сейчас использовать. Прямо очень напрашивается эта функция. Спасибо!

**Comment by agolyud** [comment]
Здравствуйте. Подумаю как можно реализовать. Мб сделаю на днях

**Comment by agolyud** [comment]
Реализаую в 1.1.2. Ожидайте

**Comment by agolyud** [comment]
Реализаую в 1.1.2. Ожидайте

**Comment by agolyud** [comment]
https://github.com/agolyud/VPN_Outline_TV/releases/tag/1.1.2

Добавил возможность добавлять несколько ключей. А так же удаление
