### ISSUE TITLE
Добавить поиск в раздел настроек "Добавить приложение"

### ISSUE THREAD

**Issue by Denis-Raev** [agolyud/VPN_Outline_TV#33]
Приветствую! Спасибо огромное за твой вклад в безопасный и свободный интернет!
Приложение отличное и интуитивное. Отдельная благодарность за реализацию возможности маршрутизировать трафик через VPN только для отдельных приложений что даёт возможность оптимизировать нагрузку на сети и сократить углеродный след в мире (осознанное потребление).

Было бы классно, если бы ты смог реализовать поисковую строку в диалоговом окне выбора приложения для маршрутизации.

**Как это сделано сейчас:** 
![photo_2024-12-07_14-27-21](https://github.com/user-attachments/assets/9b8641ae-2c00-4fa1-a69d-fd10c26884cd)

**Про что я говорю (реализация в клиенте WG Tunnel):**
![photo_2024-12-07_14-28-41](https://github.com/user-attachments/assets/60658e07-77d4-4ce5-9b64-630fb9858171)

**Что это даёт?**
Удобство выбора белого списка приложений когда на устройстве их великое множество (особенно если это диалоговое окно ещё в результатах выдаёт все системные приложения).

**Где можно подсмотреть как это реализовано?**
В проекте таких же энтузиастов как и ты WG Tunnel: https://github.com/zaneschepke/wgtunnel

_Ещё раз спасибо огромное за твою работу и всего тебе наилучшего! :)_

**Comment by agolyud** [comment]
Приветствую. Спасибо за теплые слова. Реализовал в 1.1.1 (выпущу сегодня-завтра)

![Screenshot_1733731147](https://github.com/user-attachments/assets/51a790dc-dd2d-46e9-9806-e5b2c6895346)

**Comment by agolyud** [comment]
https://github.com/agolyud/VPN_Outline_TV/releases/tag/1.1.1
