### ISSUE TITLE
Видео на ТВ не проигрывается в 4К

### ISSUE THREAD

**Issue by lfajak2** [agolyud/VPN_Outline_TV#36]
На телевизоре не проигрывается видео на ютубе в 4К или 1440P, скорости не хватает. Через оригинальный клиент Outline на ПК все летает, в том числе в 8К. Есть способы решения данной проблемы?

**Comment by agolyud** [comment]
Поменяйте днс в настройках приложения

**Comment by lfajak2** [comment]
> Поменяйте днс в настройках приложения

На какой?

**Comment by agolyud** [comment]
Не могу сказать какой лучше будет. Надо пробовать. В следующей версии вообще сделаю возможность отключить DNS ( у меня лично на Google в 4к грузит)
