### ISSUE TITLE
Need Support for Dynamic Access Keys

### ISSUE THREAD

**Issue by Marasch** [agolyud/VPN_Outline_TV#5]
It seems that app doesn't working properly with dynamic key format. raise error: "Invalid link format"

**Comment by Vitaliy39** [comment]
Присоединяюсь, papervpn не подключается с ошибкой "неправильный формат ссылки"

**Comment by agolyud** [comment]
@Marasch send a sample key. instead of ip specify 1.1.1.1:1111 I will fix the parser and it will work.

@Vitaliy39 пришлите формат ключа заменим ip на 1.1.1.1:1111 попробую поправить парсер под ваш формат. Что бы поддерживал

**Comment by Marasch** [comment]
У меня кстати тоже papervpn, но думаю проблема все-таки не в них, а более общая.
Вот пример формата динамического ключа, в явном виде порта тут нет.
ssconf://users.outline.yourvpn.io/conf/qwerty1235e0x112dd2exz#Wow!

**Comment by agolyud** [comment]
@Marasch Покупать доступ на papervpn пока нет не обходимости. По этому могу предложить отписать в телегу мне, предоставите доступ к аккаунту я разберусь как ключ шифруется и как его дешифровать. И после этого поправить парсер и выпустить билд и потом вы смените пароль. Либо взять исходник и самому реализовать. 


у меня формат ключей поддерживает только такие ss://


Пример:
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTo5Q1o5OWdSSG16cDRTbEtGMk54YXhS@195.2.76.71:60422#Russia%20#1102%20/%20

**Comment by Marasch** [comment]
@agolyud Справедливо.
Но как я писал выше, это не проприетарный формат paperVPN, это формат динамического ключа, который поддерживается стандартным клиентом Outline.
Support Paper прислал мне статический ключ, впрочем он тоже не заработал в вашем клиенте, возможно потому что вы не разбираете формат prefix (см. https://github.com/Jigsaw-Code/outline-server/issues/1328)

В итоге я сконвертировал присланный статический ключ в Json и перешел на использование ShadowSocks.
Вам спасибо и удачи в добавлении в будущем поддержки динамического ключа и prefix

**Comment by agolyud** [comment]
Добавил поддержку 
https://github.com/agolyud/VPN_Outline_TV/releases/tag/1.0.4
