### ISSUE TITLE
MIBOX4 issue

### ISSUE THREAD

**Issue by mkxxx** [agolyud/VPN_Outline_TV#6]
Соединяется (совершенно точно, сервер регистрирует соединение), через секунду отваливается.

Model: MIBOX4
Version 9
Android security patch level: 5 July 2021
Kernel version: 4.9.113
Build: PI.3933 release-keys

**Comment by agolyud** [comment]
Здравствуйте, версию ядра напишите еще. Постараюсь подумать что можно сделать

**Comment by mkxxx** [comment]
Kernel version
4.9.113
#1 Tue Sep 28 18:32:35 CST 2021

оно?

**Comment by agolyud** [comment]
Да оно гляну завтра. Отпишу тут мысли или решение

**Comment by dmitry160981** [comment]
Добрый вечер! Так же на мибоксе отваливается, видно ,что подключается потом черес 1.2.4 сек отваливается !!!

**Comment by dmitry160981** [comment]
у меня версия ядра 4.9.118+

**Comment by nosovkolia** [comment]
Аналогично. Версия 4.9.113

**Comment by sprillion** [comment]
На телевизоре Xiaomi A2 тоже такая проблема.

Версия ядра
4.19.195+ab8048

**Comment by dgaranchuk** [comment]
Bravia
4.19.75
Тоже самое, 1-2 секунды и соединение падает.

**Comment by agolyud** [comment]
Пробуйте эту версию, вроде должно работать:

https://github.com/agolyud/VPN_Outline_TV/releases/tag/1.0.3

**Comment by mkxxx** [comment]
> Пробуйте эту версию, вроде должно работать:
> 
> https://github.com/agolyud/VPN_Outline_TV/releases/tag/1.0.3

да, работает
