### ISSUE TITLE
Android TV not working

### ISSUE THREAD

**Issue by frost357** [agolyud/VPN_Outline_TV#7]
При нажатии подключить на 1-2сек подключается и сам отключается.

Версия ОС: Android TV 11
Версия ядра: 4.19.182-ab2916
Сборка ОС: RTT2.211108.001

**Comment by tigran-halatrian** [comment]
+ just very same issue. 
Unfortunately doesn't work for me.

**Comment by agolyud** [comment]
https://github.com/agolyud/VPN_Outline_TV/releases/tag/1.0.3

Попробуй этот фикс

**Comment by frost357** [comment]
> https://github.com/agolyud/VPN_Outline_TV/releases/tag/1.0.3

Помогло! Спасибо, теперь работает хорошо, за вечер ни одного обрыва.
